libraryapp/urls.py
from django.conf.urls import url
from .views import *
from django.conf.urls import url, include
from django.urls import path

app_name = "libraryapp"

urlpatterns = [
    url(r'accounts/', include('django.contrib.auth.urls')),
    url(r'^$', book_list, name='home'),
     url(r'^library$', library_list, name='library'),
    url(r'^books$', book_list, name='books'),
    url(r'^librarians$',librarian_list, name='librarians'),
    url(r'^book/form$', book_form, name='book_form'),

    url(r'^library/form$', library_form, name='library_form'),
    url(r'^libraries$', library_list, name='libraries'),
    path('books/<int:book_id>/', book_details, name='book'),
    path('books/<int:book_id>/', book_details, name='book'),
    path('librarians/<int:librarian_id>/', librarian_details, name='librarian'),
    path('library/<int:library_id>/', library_details, name='library'),
    url(r'^books/(?P<book_id>[0-9]+)/form$', book_edit_form, name='book_edit_form'),
]

librayproject/urls.py
from django.contrib import admin
from django.conf.urls import include, url
from django.urls import path
from libraryapp.models import *

urlpatterns = [
    path('admin/', admin.site.urls),
    url(r'^', include('libraryapp.urls')),
]

libraryapp/models/book.py
from django.db import models
from .library import Library
from .librarian import Librarian

class Book(models.Model):

    title = models.CharField(max_length=100)
    isbn_number = models.CharField(max_length=100)
    author = models.CharField(max_length=100)
    year_published = models.IntegerField()
    location = models.ForeignKey(Library, on_delete=models.CASCADE)
    librarian = models.ForeignKey(Librarian, on_delete=models.CASCADE)

libraryapp/models/librarian.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver
from .library import Library


class Librarian(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    location = models.ForeignKey(
        Library, related_name="librarians",
        null=True, # Makes column nullable in DB
        blank=True, # Allows blank value on objects
        on_delete=models.CASCADE)


# These receiver hooks allow you to continue to
# work with the `User` class in your Python code.


# Every time a `User` is created, a matching `Librarian`
# object will be created and attached as a one-to-one
# property
@receiver(post_save, sender=User)
def create_librarian(sender, instance, created, **kwargs):
    if created:
        Librarian.objects.create(user=instance)

# Every time a `User` is saved, its matching `Librarian`
# object will be saved.
@receiver(post_save, sender=User)
def save_librarian(sender, instance, **kwargs):
    instance.librarian.save()

libraryapp/models/library.py
from django.db import models

class Library(models.Model):


    title = models.CharField(max_length=100)
    address = models.CharField(max_length=100)

libraryapp/models/modelfactory.py
import sqlite3

# Higher order function to create instances of models
# when performing single table queries
def model_factory(model_type):
    def create(cursor, row):
        instance = model_type()
        smart_row = sqlite3.Row(cursor, row)
        for col in smart_row.keys():
            setattr(instance, col, smart_row[col])
        return instance
    return create

libraryapp/views/connection.py
class Connection:
    db_path = "/Users/MatthewMcdevitt/workspace/python/librayproject/db.sqlite3"

libraryapp/templates/books/detail.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Library</title>
</head>

<body>

   <section id="book-details">
    <h1>{{ book.title }}</h1>
    <h2>By {{ book.author }}</h2>

    <div>Published in {{ book.year_published }}</div>
    <div>ISBN: {{ book.isbn_number }}</div>
    <div>Located in the {{ book.location.title }}</div>
    <div>Registered by {{ book.librarian.first_name }} {{ book.librarian.last_name }}</div>
</section>

    <section id="book-actions" style="display:flex;">
        <form action="{% url 'libraryapp:book' book.id %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="actual_method" value="DELETE">
            <button>Delete</button>
        </form>

        <form action="{% url 'libraryapp:book_edit_form' book.id %}" method="GET">
            {% csrf_token %}
            <button>Edit</button>
        </form>
    </section>

</body>

</html>

libraryapp/templates/books/edit.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Library</title>
</head>

<body>

    <section id="book-details">
        <h1>{{ book.title }}</h1>
        <h2>By {{ book.author }}</h2>

        <div>Published in {{ book.year_published }}</div>
        <div>ISBN: {{ book.isbn_number }}</div>
    </section>

    <section id="book-actions" style="display:flex;">
        <form action="{% url 'libraryapp:book' book.id %}" method="POST">
            {% csrf_token %}
            <input type="hidden" name="actual_method" value="DELETE">
            <button>Delete</button>
        </form>

        <form action="{% url 'libraryapp:book_edit_form' book.id %}" method="GET">
            {% csrf_token %}
            <button>Edit</button>
        </form>
    </section>

</body>

</html>

libraryapp/templates/books/form.html
{% extends 'shared/base.html' %}

{% block content %}

<body>
    <h1>Inventory Book</h1>

    {% if book.id is not None %}
        <form action="{% url 'libraryapp:book' book.id %}" method="post">
    {% else %}
        <form action="{% url 'libraryapp:books' %}" method="post">
    {% endif %}
        {% csrf_token %}
        <fieldset>
            <label for="title">Title: </label>
            <input id="title" type="text" name="title" value="{{ book.title }}">
        </fieldset>
        <fieldset>
            <label for="author">Author: </label>
            <input id="author" type="text" name="author" value="{{ book.author }}">
        </fieldset>
        <fieldset>
            <label for="year_published">Year of publication: </label>
            <input id="year_published" type="number" name="year_published" value="{{ book.year_published }}">
        </fieldset>
        <fieldset>
            <label for="isbn_number">ISBN: </label>
            <input id="isbn_number" type="text" name="isbn_number" value="{{ book.isbn_number }}">
        </fieldset>
        <fieldset>
            <label for="location">Library: </label>
            <select id="location" type="text" name="location">
                {% for library in all_libraries %}
                <option {% if library.id == book.location_id %}selected{% endif %} value="{{ library.id }}">
                    {{ library.title }}</option>
                {% endfor %}
            </select>
        </fieldset>

        {% if book.id is not None %}
            <input type="hidden" name="actual_method" value="PUT">
            <input type="submit" value="Update" />
        {% else %}
            <input type="submit" value="Create" />
        {% endif %}

    </form>
{% endblock %}

libraryapp/templates/books/list.html
{% extends 'shared/base.html' %}
{% load staticfiles %}

{% block css %}
    <link rel="stylesheet" href="{% static 'styles/books.css' %}" />
{% endblock %}

{% block content %}
    <h1>Books</h1>

    <a href="{% url 'libraryapp:book_form' %}">Add Book to Inventory</a>

    <ol class="books">
    {% for book in all_books %}
        <li class="book">
            <a class="book__title" href="{% url 'libraryapp:book' book.id %}"> {{ book.title }}</a>
            <div class="book__description">
                by {{book.author}} published in {{book.year_published}}
            </div>
        </li>
    {% endfor %}
    </ol>
{% endblock %}

libraryapp/templates/librarians/detail.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Librarians</title>
  </head>
  <body>
    <h1>{{librarian.first_name }} {{librarian.last_name}}</h1>

    <div>Email: {{ librarian.email}}</div>
    <div>Location: {{ librarian.location }}</div>
  </body>
</html>

libraryapp/templates/librarians/list.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Library</title>
  </head>
  <body>
    <h1>Librarians</h1>

    <ol>
    {% for librarian in all_librarians %}
        <li>{{ librarian.first_name }} {{ librarian.last_name }}</li>
        <a href="{% url 'libraryapp:librarian' librarian.id %}"> {{ librarian.email}} </a>

        </li>
    {% endfor %}
    </ol>
  </body>
</html>

libraryapp/templates/libraries/details.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Library</title>
  </head>
  <body>
    <h1>{{ library.title }}</h1>
    <h2> {{ library.address }}</h2>
  </body>
</html>

libraryapp/templates/libraries/form.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Bangazon</title>
  </head>
  <body>
    <h1>Add Library Location</h1>


    <form action="{% url 'libraryapp:libraries' %}" method="post">
      {% csrf_token %}
      <fieldset>
          <label for="title">Title: </label>
          <input id="title" type="text" name="title">
      </fieldset>
      <fieldset>
          <label for="address">Address: </label>
          <input id="address" type="text" name="address">
      <input type="submit" value="Add It" />
    </form>
  </body>
</html>

libraryapp/templates/libraries/list.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <title>Library</title>
  </head>
  <body>
    <h1>Library</h1>

    <ol>
    {% for library in all_libraries %}
        <li>
            {{ library.title }}
            at {{library.address}}
            <a href "{% url 'libraryapp:library' library.id %}"> click here</a>
        </li>
    {% endfor %}
    </ol>
  </body>
</html>

libraryapp/templates/shared/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8">
    <title>Library</title>

    <link rel="stylesheet" href="{% static 'styles/base.css' %}" />

    {% block css %}
    {% endblock %}
</head>

<body>

    <nav id="site-nav">
        <ol class="navList">
            <li class="navList__route"><a href="{% url 'libraryapp:home' %}">Home</a></li>
            <li class="navList__route"><a href="{% url 'libraryapp:libraries' %}">Libraries</a></li>
            <li class="navList__route"><a href="{% url 'libraryapp:books' %}">Books</a></li>
            <li class="navList__route"><a href="{% url 'libraryapp:librarians' %}">Librarians</a></li>
            <li class="navList__route"><a href="{% url 'libraryapp:logout' %}">Logout</a></li>
        </ol>
    </nav>

    <main class="main-content">
        {% block content %}
        {% endblock %}
    </main>

    {% block scripts %}
    {% endblock scripts %}
</body>

</html>